# Site settings
site: jakkalster
title: Minimal blog
keywords: blog
description: >-
  Just some minimal blog
lang: en-US
timezone:  Asia/Kuching
#repo:  # site repo [optional]
#google_verify:       # Put your Google Verification here
#google_analytics:   # Put your Google Analytics code
#discus-identifier:  

# Author settings
author:
  name: jakkalster
  bio: Just a guy who loves tech, gaming and stuff /#gaming /#linux
  picture: https://avatars.githubusercontent.com/u/90917974?s=400&v=4
  #github: onepase # github username
  #twitter: onepase # twitter username
  #facebook: onepase # facebook username
  #instagram: onepase # instagram username
  #youtube: https://www.youtube.com/channel/UCMmAto-wxBootXN91AzBiDg # youtube username
  #linkedin: hakantorun # linkedin username
  #email: your-email@email.com # email adress


# URL settings
url: "jakkalster.github.io" # Domain Name of host. [username].github.io for github pages
permalink: pretty

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge


exclude:
  - .jekyll-cache
  - .obsidian
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - CONTRIBUTING.md

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-relative-links
paginate: 20
paginate_path: "/page/:num"

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /:slug
  
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

relative_links:
  enabled:     true
  collections: false
